version: '{build}'
image: Visual Studio 2017

before_build:
  - nuget restore
after_build:
  - 7z a YoutubeDotMp3.zip %APPVEYOR_BUILD_FOLDER%\bin\Release\*
  
configuration: Release

build:
  verbosity: minimal
  
artifacts:
  - path: YoutubeDotMp3.zip

deploy:
  - provider: GitHub
    artifact: YoutubeDotMp3.zip
    release: ${appveyor_repo_tag_name}
    description: 'Version ${appveyor_repo_tag_name}'
    force_update: true
    auth_token:
      secure: NFu7VATIRtpS96dnh27gq3AgyBTDfD/RvLNcdgG5N0HKXYUjHZoEIMoMaFjMD6Za
    on:
      branch: master
      configuration: Release
      appveyor_repo_tag: true