name: Change
on:
  workflow_dispatch:
  push:
    branches: ['**']
    tags-ignore: ['**']
  pull_request:
    branches: ['**']
    tags-ignore: ['**']
jobs:
  windows-validate:
    name: windows
    uses: ReMinoer/workflows/.github/workflows/dotnet-validate.yml@master
    with:
      os: windows-latest
      solution_file: YoutubeDotMp3.sln
      pack: false
