name: Release
on:
  release:
    types: [published]
jobs:
  dotnet-release:
    name: dotnet
    uses: ReMinoer/workflows/.github/workflows/dotnet-release.yml@master
    with:
      os: "['windows-latest']"
      solution_file: YoutubeDotMp3.sln
      project_folder: YoutubeDotMp3
      target_framework: net48
      zip_prefix: YoutubeDotMp3
      dotnet_version: 4.8